/**
 * Mock data loaded when the app runs with no saved state.
 * Two clients: NZICC (Attendee Experience → Attend Conference, Attend Concert),
 * RocketLab (Human Payload → Application for Astronaut, Medical Check).
 *
 * Jobs are created as top-level entities (Jobs tab) and assigned to phases via jobIds.
 */

import type { AppState, Client, Project, Journey, Phase, Job, Opportunity, OpportunityStage, Insight } from '@/types';
import { parseOpportunities } from '@/lib/utils';

const TS = '2025-01-15T10:00:00.000Z';

function emptyPhase(overrides: Partial<Phase> & { id: string; journeyId: string; order: number }): Phase {
  return {
    id: overrides.id,
    journeyId: overrides.journeyId,
    order: overrides.order,
    title: overrides.title ?? '',
    description: overrides.description ?? '',
    imageUrl: '',
    struggles: overrides.struggles ?? '',
    internalStruggles: overrides.internalStruggles ?? '',
    relatedDocuments: overrides.relatedDocuments ?? '',
    opportunities: overrides.opportunities ?? '',
    frontStageActions: overrides.frontStageActions ?? '',
    backStageActions: overrides.backStageActions ?? '',
    systems: overrides.systems ?? '',
    relatedProcesses: overrides.relatedProcesses ?? '',
    channels: overrides.channels ?? '',
    jobIds: overrides.jobIds ?? [],
    customRowValues: {},
    createdAt: TS,
    updatedAt: TS,
  };
}

/** Fixed set of 12 contextually relevant demo jobs (NZICC + Rocket Lab) */
function getDemoJobs(): Job[] {
  return [
    { id: 'demo-job-1', clientId: 'demo-client-nzicc', name: 'Understand event value and relevance', description: 'Evaluate whether the conference fits my goals and schedule', tag: 'Functional', priority: 'High', insightIds: [], createdAt: TS, updatedAt: TS },
    { id: 'demo-job-2', clientId: 'demo-client-nzicc', name: 'Secure a place quickly', description: 'Complete registration and payment with minimal friction', tag: 'Functional', priority: 'High', insightIds: [], createdAt: TS, updatedAt: TS },
    { id: 'demo-job-3', clientId: 'demo-client-nzicc', name: 'Build my agenda and avoid session clashes', description: 'Select sessions and plan the day without overlaps', tag: 'Functional', priority: 'High', insightIds: [], createdAt: TS, updatedAt: TS },
    { id: 'demo-job-4', clientId: 'demo-client-nzicc', name: 'Find out about the event', description: 'Discover the concert and check dates, venue, and availability', tag: 'Functional', priority: 'Medium', insightIds: [], createdAt: TS, updatedAt: TS },
    { id: 'demo-job-5', clientId: 'demo-client-nzicc', name: 'Get tickets at a fair price', description: 'Purchase tickets without queue drops or scalping concerns', tag: 'Functional', priority: 'High', insightIds: [], createdAt: TS, updatedAt: TS },
    { id: 'demo-job-6', clientId: 'demo-client-nzicc', name: 'Access session content after the event', description: 'Get slides and recordings in one place post-conference', tag: 'Functional', priority: 'Medium', insightIds: [], createdAt: TS, updatedAt: TS },
    { id: 'demo-job-7', clientId: 'demo-client-rocketlab', name: 'Present my qualifications clearly', description: 'Submit a strong application with clear criteria and examples', tag: 'Functional', priority: 'High', insightIds: [], createdAt: TS, updatedAt: TS },
    { id: 'demo-job-8', clientId: 'demo-client-rocketlab', name: 'Know my status through the process', description: 'Receive timeline and status updates during screening', tag: 'Functional', priority: 'High', insightIds: [], createdAt: TS, updatedAt: TS },
    { id: 'demo-job-9', clientId: 'demo-client-rocketlab', name: 'Book medical evaluation at a time that works', description: 'Schedule the appointment and know what to bring', tag: 'Functional', priority: 'Medium', insightIds: [], createdAt: TS, updatedAt: TS },
    { id: 'demo-job-10', clientId: 'demo-client-rocketlab', name: 'Complete forms and arrive prepared', description: 'Submit pre-visit forms and follow prep instructions', tag: 'Functional', priority: 'Medium', insightIds: [], createdAt: TS, updatedAt: TS },
    { id: 'demo-job-11', clientId: 'demo-client-nzicc', name: 'Understand today\'s events and priorities', description: 'Receive handover and run sheet for the shift', tag: 'Functional', priority: 'Medium', insightIds: [], createdAt: TS, updatedAt: TS },
    { id: 'demo-job-12', clientId: 'demo-client-nzicc', name: 'Verify all spaces are ready', description: 'Complete pre-event inspections and log any issues', tag: 'Functional', priority: 'Medium', insightIds: [], createdAt: TS, updatedAt: TS },
  ];
}

/** Which phase(s) each demo job is assigned to (phaseId -> jobIds) */
const DEMO_PHASE_JOB_IDS: Record<string, string[]> = {
  'demo-phase-conf-1': ['demo-job-1'],
  'demo-phase-conf-2': ['demo-job-2'],
  'demo-phase-conf-3': ['demo-job-3'],
  'demo-phase-conf-5': ['demo-job-6'],
  'demo-phase-concert-1': ['demo-job-4'],
  'demo-phase-concert-2': ['demo-job-5'],
  'demo-phase-astro-1': ['demo-job-7'],
  'demo-phase-astro-2': ['demo-job-8'],
  'demo-phase-med-1': ['demo-job-9'],
  'demo-phase-med-2': ['demo-job-10'],
  'demo-phase-fac-1': ['demo-job-11'],
  'demo-phase-fac-2': ['demo-job-12'],
};

/** Build top-level opportunities from phase.opportunities */
function buildOpportunitiesFromPhases(
  phases: Phase[],
  journeys: Journey[],
  projects: Project[]
): Opportunity[] {
  const result: Opportunity[] = [];
  const H1: OpportunityStage = 'Horizon 1';
  const H2: OpportunityStage = 'Horizon 2';
  const H3: OpportunityStage = 'Horizon 3';
  let idx = 0;
  for (const phase of phases) {
    const journey = journeys.find((j) => j.id === phase.journeyId);
    const project = journey ? projects.find((p) => p.id === journey.projectId) : null;
    if (!journey || !project) continue;
    const items = parseOpportunities(phase.opportunities ?? '');
    items.forEach((item) => {
      result.push({
        id: item.id,
        clientId: project.clientId,
        projectId: project.id,
        journeyId: journey.id,
        phaseId: phase.id,
        stage: idx < 4 ? H1 : idx < 8 ? H2 : idx < 12 ? H3 : 'Backlog',
        stageOrder: idx < 4 ? idx : idx < 8 ? idx - 4 : idx < 12 ? idx - 8 : 0,
        name: item.name,
        priority: (item.tag as Opportunity['priority']) || 'High',
        description: item.description ?? '',
        pointOfDifferentiation: item.pointOfDifferentiation ?? '',
        criticalAssumptions: item.criticalAssumptions ?? '',
        linkedJobIds: [],
        isPriority: !!item.isPriority,
        createdAt: TS,
        updatedAt: TS,
      });
      idx++;
    });
  }
  return result;
}

export function getDemoState(): Pick<AppState, 'clients' | 'projects' | 'journeys' | 'phases' | 'jobs' | 'insights' | 'opportunities' | 'cellComments'> {
  const clients: Client[] = [
    {
      id: 'demo-client-nzicc',
      name: 'NZICC',
      description: 'New Zealand International Convention Centre. World-class events and conferences in Auckland.',
      website: 'https://www.nzicc.co.nz',
      logoUrl: 'https://logo.clearbit.com/nzicc.co.nz',
      createdAt: TS,
      updatedAt: TS,
    },
    {
      id: 'demo-client-rocketlab',
      name: 'Rocket Lab',
      description: 'Private aerospace manufacturer and small satellite launch provider.',
      website: 'https://www.rocketlabusa.com',
      logoUrl: 'https://logo.clearbit.com/rocketlabusa.com',
      createdAt: TS,
      updatedAt: TS,
    },
  ];

  const projects: Project[] = [
    { id: 'demo-project-attendee', clientId: 'demo-client-nzicc', name: 'Attendee Experience', description: 'End-to-end journey for conference and event attendees', createdAt: TS, updatedAt: TS },
    { id: 'demo-project-venueops', clientId: 'demo-client-nzicc', name: 'Venue Operations', description: 'Day-to-day venue management and operations', createdAt: TS, updatedAt: TS },
    { id: 'demo-project-exhibitor', clientId: 'demo-client-nzicc', name: 'Exhibitor Experience', description: 'Exhibitor journey from booking to show day', createdAt: TS, updatedAt: TS },
    { id: 'demo-project-corporate', clientId: 'demo-client-nzicc', name: 'Corporate Events', description: 'Corporate meeting and event booking experience', createdAt: TS, updatedAt: TS },
    { id: 'demo-project-humanpayload', clientId: 'demo-client-rocketlab', name: 'Human Payload', description: 'Crew selection and readiness for human spaceflight', createdAt: TS, updatedAt: TS },
    { id: 'demo-project-satellite', clientId: 'demo-client-rocketlab', name: 'Satellite Operations', description: 'Customer launch operations and mission management', createdAt: TS, updatedAt: TS },
    { id: 'demo-project-customersupport', clientId: 'demo-client-rocketlab', name: 'Customer Support', description: 'Post-sale customer onboarding and support', createdAt: TS, updatedAt: TS },
    { id: 'demo-project-rd', clientId: 'demo-client-rocketlab', name: 'R&D Partnerships', description: 'Research collaboration and technology development', createdAt: TS, updatedAt: TS },
  ];

  const journeys: Journey[] = [
    { id: 'demo-journey-conference', projectId: 'demo-project-attendee', name: 'Attend Conference', description: 'From first awareness to post-event engagement', rowOrder: undefined, customRows: [], createdAt: TS, updatedAt: TS },
    { id: 'demo-journey-concert', projectId: 'demo-project-attendee', name: 'Attend Concert', description: 'Live music event experience lifecycle', rowOrder: undefined, customRows: [], createdAt: TS, updatedAt: TS },
    { id: 'demo-journey-facilitymgmt', projectId: 'demo-project-venueops', name: 'Facility Management', description: 'Venue operations and maintenance workflow', rowOrder: undefined, customRows: [], createdAt: TS, updatedAt: TS },
    { id: 'demo-journey-exhibitor', projectId: 'demo-project-exhibitor', name: 'Exhibitor Journey', description: 'From stand booking to event day', rowOrder: undefined, customRows: [], createdAt: TS, updatedAt: TS },
    { id: 'demo-journey-corporatebook', projectId: 'demo-project-corporate', name: 'Corporate Booking', description: 'Meeting and event inquiry to confirmation', rowOrder: undefined, customRows: [], createdAt: TS, updatedAt: TS },
    { id: 'demo-journey-astronaut', projectId: 'demo-project-humanpayload', name: 'Application for Astronaut', description: 'Candidate journey from application to selection', rowOrder: undefined, customRows: [], createdAt: TS, updatedAt: TS },
    { id: 'demo-journey-medical', projectId: 'demo-project-humanpayload', name: 'Medical Check', description: 'Medical evaluation and clearance for crew', rowOrder: undefined, customRows: [], createdAt: TS, updatedAt: TS },
    { id: 'demo-journey-launchops', projectId: 'demo-project-satellite', name: 'Launch Operations', description: 'Mission integration through launch', rowOrder: undefined, customRows: [], createdAt: TS, updatedAt: TS },
    { id: 'demo-journey-onboarding', projectId: 'demo-project-customersupport', name: 'Customer Onboarding', description: 'New customer setup and handover', rowOrder: undefined, customRows: [], createdAt: TS, updatedAt: TS },
    { id: 'demo-journey-collab', projectId: 'demo-project-rd', name: 'Research Collaboration', description: 'Partner engagement and joint development', rowOrder: undefined, customRows: [], createdAt: TS, updatedAt: TS },
  ];

  const phases: Phase[] = [
    // —— Attend Conference ——
    emptyPhase({
      id: 'demo-phase-conf-1',
      journeyId: 'demo-journey-conference',
      order: 1,
      title: 'Discovery & Consideration',
      description: 'Potential attendee becomes aware of the event and evaluates whether to attend.',
      customerJobs: JSON.stringify([{ text: 'Understand event value and relevance', tag: 'Functional', isPriority: true }, { text: 'Check dates and fit with schedule', tag: 'Functional' }, { text: 'Feel excited about the experience', tag: 'Emotional', isPriority: true }]),
      frontStageActions: 'Search for events\nBrowse NZICC website\nRead programme\nCompare with other events\nCheck speaker lineup',
      struggles: JSON.stringify([{ text: 'Information scattered across sources', tag: 'High' }, { text: 'Unclear pricing and what\'s included', tag: 'Medium' }]),
      internalStruggles: JSON.stringify([{ text: 'Content spread across multiple systems', tag: 'High' }, { text: 'Slow approval process for programme updates', tag: 'Medium' }]),
      opportunities: JSON.stringify([
        { id: 'opp-conf-1a', name: 'Unified event hub', tag: 'High', isPriority: true },
        { id: 'opp-conf-1b', name: 'Personalised recommendations', tag: 'Medium' },
      ]),
      relatedDocuments: JSON.stringify([
        { id: 'doc-conf-1a', label: 'Event Programme (SharePoint)', url: 'https://contoso.sharepoint.com/sites/events/programme-2025' },
        { id: 'doc-conf-1b', label: 'Discovery Phase Confluence', url: 'https://nzicc.atlassian.net/wiki/spaces/EVENTS/pages/discovery-phase' },
      ]),
      backStageActions: 'Content team updates programme\nMarketing runs campaigns\nSales handles enquiries',
      systems: 'CMS\nCRM\nEmail platform',
      relatedProcesses: 'Event programming\nSponsorship sales\nVenue operations',
    }),
    emptyPhase({
      id: 'demo-phase-conf-2',
      journeyId: 'demo-journey-conference',
      order: 2,
      title: 'Registration & Booking',
      description: 'Committing to attend and completing registration and payment.',
      customerJobs: JSON.stringify([{ text: 'Secure a place quickly', tag: 'Functional', isPriority: true }, { text: 'Choose the right ticket type', tag: 'Functional' }, { text: 'Get confirmation and peace of mind', tag: 'Emotional' }]),
      frontStageActions: 'Select ticket type\nEnter details\nPay\nReceive confirmation\nAdd to calendar',
      struggles: JSON.stringify([{ text: 'Form length and friction', tag: 'Medium' }, { text: 'Unclear refund policy', tag: 'Low' }]),
      internalStruggles: JSON.stringify([{ text: 'Integration gaps between reg platform and CRM', tag: 'High' }]),
      opportunities: JSON.stringify([
        { id: 'opp-conf-2a', name: 'One-click rebook for returning attendees', tag: 'High' },
        { id: 'opp-conf-2b', name: 'Group booking flow', tag: 'Medium' },
      ]),
      relatedDocuments: JSON.stringify([
        { id: 'doc-conf-2a', label: 'Registration Jira Epic', url: 'https://nzicc.atlassian.net/browse/EVT-142' },
        { id: 'doc-conf-2b', label: 'Refund Policy (SharePoint)', url: 'https://contoso.sharepoint.com/sites/events/policies/refund' },
      ]),
      backStageActions: 'Process payments\nIssue tickets\nUpdate attendee list\nHandle exceptions',
      systems: 'Registration system\nFinance / reconciliation',
      relatedProcesses: 'Finance\nCustomer support',
    }),
    emptyPhase({
      id: 'demo-phase-conf-3',
      journeyId: 'demo-journey-conference',
      order: 3,
      title: 'Pre-Event Prep',
      description: 'Between booking and arrival: logistics, agenda, and expectations.',
      customerJobs: JSON.stringify([{ text: 'Plan travel and accommodation', tag: 'Functional' }, { text: 'Build my agenda', tag: 'Functional', isPriority: true }, { text: 'Connect with other attendees', tag: 'Social', isPriority: true }]),
      frontStageActions: 'Receive pre-event emails\nDownload app\nSelect sessions\nBook workshops\nView venue map',
      struggles: JSON.stringify([{ text: 'Too many emails', tag: 'Medium' }, { text: 'Session clashes', tag: 'High' }]),
      opportunities: JSON.stringify([
        { id: 'opp-conf-3a', name: 'Smart agenda builder with conflict detection', tag: 'High' },
      ]),
      backStageActions: 'Send comms\nUpdate programme\nManage waitlists\nBrief speakers',
      systems: 'Event app backend\nEmail automation',
      relatedProcesses: 'Programme management\nLogistics',
    }),
    emptyPhase({
      id: 'demo-phase-conf-4',
      journeyId: 'demo-journey-conference',
      order: 4,
      title: 'At the Conference',
      description: 'On-site experience: sessions, networking, and logistics.',
      customerJobs: JSON.stringify([{ text: 'Learn from sessions', tag: 'Functional', isPriority: true }, { text: 'Network effectively', tag: 'Social' }, { text: 'Feel welcome and oriented', tag: 'Emotional', isPriority: true }]),
      frontStageActions: 'Arrive and check in\nNavigate venue\nAttend sessions\nUse app for updates\nVisit expo\nNetwork',
      struggles: JSON.stringify([{ text: 'Finding rooms and people', tag: 'Medium' }, { text: 'Queue times for food', tag: 'Low' }]),
      opportunities: JSON.stringify([
        { id: 'opp-conf-4a', name: 'Real-time wayfinding and meet-up', tag: 'High' },
      ]),
      backStageActions: 'Run registration desk\nAV and room support\nCatering\nSafety and access',
      systems: 'Badge / access\nEvent app\nCatering systems',
      relatedProcesses: 'Venue ops\nAV\nCatering',
    }),
    emptyPhase({
      id: 'demo-phase-conf-5',
      journeyId: 'demo-journey-conference',
      order: 5,
      title: 'Follow-up & Engagement',
      description: 'After the event: content, connections, and next steps.',
      customerJobs: JSON.stringify([{ text: 'Access session content', tag: 'Functional' }, { text: 'Stay in touch with contacts', tag: 'Social' }, { text: 'Decide on next year', tag: 'Functional' }]),
      frontStageActions: 'Receive follow-up email\nDownload slides\nConnect on LinkedIn\nComplete survey\nConsider next event',
      struggles: JSON.stringify([{ text: 'Content arrives late', tag: 'Medium' }]),
      opportunities: JSON.stringify([
        { id: 'opp-conf-5a', name: 'Post-event community and content hub', tag: 'High' },
      ]),
      backStageActions: 'Collate and publish content\nSend survey\nAnalyse feedback\nPlan next event',
      systems: 'CMS\nSurvey platform\nCRM',
      relatedProcesses: 'Marketing\nContent',
    }),

    // —— Attend Concert ——
    emptyPhase({
      id: 'demo-phase-concert-1',
      journeyId: 'demo-journey-concert',
      order: 1,
      title: 'Discovery',
      description: 'Hearing about the concert and deciding to go.',
      customerJobs: JSON.stringify([{ text: 'Find out about the event', tag: 'Functional' }, { text: 'Check if friends are interested', tag: 'Social' }, { text: 'Get excited about the night', tag: 'Emotional' }]),
      frontStageActions: 'See social or ad\nCheck artist and venue\nLook up date and time\nShare with friends',
      struggles: JSON.stringify([{ text: 'Missing presale or early bird', tag: 'Medium' }]),
      opportunities: JSON.stringify([
        { id: 'opp-concert-1a', name: 'Artist-fan notification for NZ dates', tag: 'High' },
      ]),
      backStageActions: 'Promote event\nManage artist relations\nSet onsale dates',
      systems: 'Ticketing platform\nMarketing',
      relatedProcesses: 'Programming\nMarketing',
    }),
    emptyPhase({
      id: 'demo-phase-concert-2',
      journeyId: 'demo-journey-concert',
      order: 2,
      title: 'Ticket Purchase',
      description: 'Buying tickets before they sell out.',
      customerJobs: JSON.stringify([{ text: 'Get tickets at a fair price', tag: 'Functional' }, { text: 'Sit with my group', tag: 'Social' }]),
      frontStageActions: 'Join queue at onsale\nSelect seats or tier\nPay\nReceive e-tickets',
      struggles: JSON.stringify([{ text: 'Queue drops or timeouts', tag: 'High' }, { text: 'Resale and scalping', tag: 'High' }]),
      opportunities: JSON.stringify([
        { id: 'opp-concert-2a', name: 'Fair queue and anti-scalping', tag: 'High' },
      ]),
      backStageActions: 'Run onsale\nManage inventory\nFraud checks',
      systems: 'Ticketing\nPayments',
      relatedProcesses: 'Finance\nIT',
    }),
    emptyPhase({
      id: 'demo-phase-concert-3',
      journeyId: 'demo-journey-concert',
      order: 3,
      title: 'Pre-Show',
      description: 'Between purchase and show night.',
      customerJobs: JSON.stringify([{ text: 'Plan transport and meet-up', tag: 'Functional' }, { text: 'Know what to expect', tag: 'Emotional' }]),
      frontStageActions: 'Receive reminder emails\nCheck door time and rules\nPlan route\nCoordinate with group',
      struggles: JSON.stringify([]),
      opportunities: JSON.stringify([{ id: 'opp-concert-3a', name: 'Journey and parking info in one place', tag: 'Medium' }]),
      backStageActions: 'Send comms\nFinalise run sheet\nBrief staff',
      systems: 'Email\nVenue ops',
      relatedProcesses: 'Operations',
    }),
    emptyPhase({
      id: 'demo-phase-concert-4',
      journeyId: 'demo-journey-concert',
      order: 4,
      title: 'At the Venue',
      description: 'Arrival, entry, and the live experience.',
      customerJobs: JSON.stringify([{ text: 'Get in smoothly', tag: 'Functional' }, { text: 'Enjoy the performance', tag: 'Emotional' }, { text: 'Feel safe', tag: 'Emotional' }]),
      frontStageActions: 'Arrive\nQueue if needed\nScan ticket\nFind seat or spot\nBuy drinks/merch\nWatch show',
      struggles: JSON.stringify([{ text: 'Long entry or bar queues', tag: 'Medium' }]),
      opportunities: JSON.stringify([{ id: 'opp-concert-4a', name: 'Cashless and faster F&B', tag: 'Medium' }]),
      backStageActions: 'Doors and security\nF&B\nArtist liaison\nSafety',
      systems: 'Access control\nPOS\nCCTV',
      relatedProcesses: 'Security\nF&B',
    }),
    emptyPhase({
      id: 'demo-phase-concert-5',
      journeyId: 'demo-journey-concert',
      order: 5,
      title: 'Post-Experience',
      description: 'After the show: getting home and remembering the night.',
      customerJobs: JSON.stringify([{ text: 'Get home safely', tag: 'Functional' }, { text: 'Relive and share the experience', tag: 'Social' }]),
      frontStageActions: 'Exit venue\nTravel home\nPost on social\nSign up for next announcements',
      struggles: JSON.stringify([]),
      opportunities: JSON.stringify([{ id: 'opp-concert-5a', name: 'Post-show photo and fan content', tag: 'Low' }]),
      backStageActions: 'Venue clear-down\nDebrief\nMarketing capture',
      systems: 'CRM\nEmail',
      relatedProcesses: 'Marketing',
    }),

    // —— Application for Astronaut ——
    emptyPhase({
      id: 'demo-phase-astro-1',
      journeyId: 'demo-journey-astronaut',
      order: 1,
      title: 'Application Submission',
      description: 'Candidate submits initial application and supporting materials.',
      customerJobs: JSON.stringify([{ text: 'Present my qualifications clearly', tag: 'Functional', isPriority: true }, { text: 'Understand what is required', tag: 'Functional' }, { text: 'Feel my application is fairly considered', tag: 'Emotional', isPriority: true }]),
      frontStageActions: 'Read criteria and FAQ\nPrepare CV and cover\nComplete application form\nSubmit before deadline',
      struggles: JSON.stringify([{ text: 'Unclear criteria or process', tag: 'High' }, { text: 'Technical issues with upload', tag: 'Medium' }]),
      internalStruggles: JSON.stringify([{ text: 'ATS configuration limits custom fields', tag: 'Medium' }, { text: 'Legal review bottleneck for criteria', tag: 'High' }]),
      opportunities: JSON.stringify([
        { id: 'opp-astro-1a', name: 'Clear rubric and example applications', tag: 'High', isPriority: true },
      ]),
      relatedDocuments: JSON.stringify([
        { id: 'doc-astro-1a', label: 'Application Criteria (Confluence)', url: 'https://rocketlab.atlassian.net/wiki/spaces/CREW/pages/application-criteria' },
        { id: 'doc-astro-1b', label: 'Recruitment Jira Board', url: 'https://rocketlab.atlassian.net/jira/software/projects/CREW/boards/12' },
        { id: 'doc-astro-1c', label: 'HR Onboarding SharePoint', url: 'https://rocketlab.sharepoint.com/sites/hr/recruitment' },
      ]),
      backStageActions: 'Publish criteria\nSupport applicants\nTriage submissions',
      systems: 'ATS\nHR systems',
      relatedProcesses: 'Recruitment\nLegal',
    }),
    emptyPhase({
      id: 'demo-phase-astro-2',
      journeyId: 'demo-journey-astronaut',
      order: 2,
      title: 'Initial Screening',
      description: 'Review of applications and first-round decisions.',
      customerJobs: JSON.stringify([{ text: 'Know my status', tag: 'Functional' }, { text: 'Receive respectful communication', tag: 'Emotional' }]),
      frontStageActions: 'Receive acknowledgment\nCheck portal for updates\nRespond to any requests for info',
      struggles: JSON.stringify([{ text: 'Long wait without feedback', tag: 'High' }]),
      opportunities: JSON.stringify([{ id: 'opp-astro-2a', name: 'Timeline and status updates', tag: 'High', isPriority: true }]),
      backStageActions: 'Review applications\nShortlist\nSend updates\nSchedule next round',
      systems: 'ATS\nCalendar',
      relatedProcesses: 'Recruitment\nMedical liaison',
    }),
    emptyPhase({
      id: 'demo-phase-astro-3',
      journeyId: 'demo-journey-astronaut',
      order: 3,
      title: 'Assessment Centre',
      description: 'In-person or remote assessments: technical, physical, and behavioural.',
      customerJobs: JSON.stringify([{ text: 'Demonstrate my capabilities', tag: 'Functional' }, { text: 'Understand what is being assessed', tag: 'Functional' }, { text: 'Manage stress and perform', tag: 'Emotional' }]),
      frontStageActions: 'Receive invite and brief\nTravel if required\nComplete assessments\nInterviews and exercises',
      struggles: JSON.stringify([{ text: 'Unclear assessment format', tag: 'Medium' }, { text: 'Logistics and travel', tag: 'Medium' }]),
      opportunities: JSON.stringify([
        { id: 'opp-astro-3a', name: 'Structured prep and expectations', tag: 'High', isPriority: true },
      ]),
      backStageActions: 'Design and run assessments\nBrief assessors\nCollate scores\nMedical liaison',
      systems: 'Assessment tools\nScheduling',
      relatedProcesses: 'Medical\nSafety',
    }),
    emptyPhase({
      id: 'demo-phase-astro-4',
      journeyId: 'demo-journey-astronaut',
      order: 4,
      title: 'Selection & Offer',
      description: 'Final selection and offer of a place in the programme.',
      customerJobs: JSON.stringify([{ text: 'Receive a clear decision', tag: 'Functional' }, { text: 'Understand next steps if selected', tag: 'Functional' }, { text: 'Receive feedback if not', tag: 'Emotional' }]),
      frontStageActions: 'Receive call or email\nReview offer and terms\nAccept or decline\nComplete paperwork',
      struggles: JSON.stringify([{ text: 'Uncertainty during final decision', tag: 'High' }]),
      opportunities: JSON.stringify([{ id: 'opp-astro-4a', name: 'Transparent timeline and feedback', tag: 'High' }]),
      backStageActions: 'Panel decision\nMedical sign-off\nLegal and contracts\nOnboarding prep',
      systems: 'HR\nLegal\nMedical',
      relatedProcesses: 'Legal\nMedical',
    }),
    emptyPhase({
      id: 'demo-phase-astro-5',
      journeyId: 'demo-journey-astronaut',
      order: 5,
      title: 'Pre-Flight Onboarding',
      description: 'From offer acceptance to readiness for training and flight.',
      customerJobs: JSON.stringify([{ text: 'Complete all requirements', tag: 'Functional' }, { text: 'Build trust with team', tag: 'Social' }, { text: 'Feel prepared and supported', tag: 'Emotional' }]),
      frontStageActions: 'Complete forms and checks\nAttend orientation\nBegin training modules\nMeet team and instructors',
      struggles: JSON.stringify([{ text: 'Volume of admin and training', tag: 'Medium' }]),
      opportunities: JSON.stringify([{ id: 'opp-astro-5a', name: 'Single onboarding checklist and support', tag: 'Medium' }]),
      backStageActions: 'Run onboarding\nCoordinate medical and training\nPlan first flight phase',
      systems: 'LMS\nHR\nMedical',
      relatedProcesses: 'Training\nMedical',
    }),

    // —— Medical Check ——
    emptyPhase({
      id: 'demo-phase-med-1',
      journeyId: 'demo-journey-medical',
      order: 1,
      title: 'Scheduling',
      description: 'Candidate or crew schedules the medical evaluation.',
      customerJobs: JSON.stringify([{ text: 'Book at a time that works', tag: 'Functional' }, { text: 'Know what to bring and expect', tag: 'Functional' }]),
      frontStageActions: 'Receive referral or instruction\nContact facility or portal\nChoose date and time\nReceive confirmation',
      struggles: JSON.stringify([{ text: 'Limited availability', tag: 'Medium' }]),
      opportunities: JSON.stringify([{ id: 'opp-med-1a', name: 'Self-serve booking and prep pack', tag: 'High' }]),
      backStageActions: 'Manage capacity\nSend confirmations\nPrepare packs',
      systems: 'Scheduling\nCRM',
      relatedProcesses: 'Clinical admin',
    }),
    emptyPhase({
      id: 'demo-phase-med-2',
      journeyId: 'demo-journey-medical',
      order: 2,
      title: 'Pre-Visit Preparation',
      description: 'Instructions, forms, and readiness before the appointment.',
      customerJobs: JSON.stringify([{ text: 'Complete forms correctly', tag: 'Functional' }, { text: 'Arrive prepared', tag: 'Functional' }]),
      frontStageActions: 'Receive prep pack\nComplete health questionnaire\nFast or adjust meds if required\nPlan travel',
      struggles: JSON.stringify([{ text: 'Unclear instructions', tag: 'Medium' }]),
      opportunities: JSON.stringify([{ id: 'opp-med-2a', name: 'Digital forms and clear checklist', tag: 'Medium' }]),
      backStageActions: 'Send prep materials\nReview submissions\nPrepare for appointment',
      systems: 'Forms\nEHR',
      relatedProcesses: 'Clinical',
    }),
    emptyPhase({
      id: 'demo-phase-med-3',
      journeyId: 'demo-journey-medical',
      order: 3,
      title: 'At the Facility',
      description: 'Day of the medical: checks, tests, and consultations.',
      customerJobs: JSON.stringify([{ text: 'Complete all required checks', tag: 'Functional' }, { text: 'Understand what is being done', tag: 'Functional' }, { text: 'Feel respected and safe', tag: 'Emotional' }]),
      frontStageActions: 'Arrive and check in\nVitals and history\nPhysical exam\nLab and imaging\nConsultation with physician',
      struggles: JSON.stringify([{ text: 'Long wait times', tag: 'Medium' }, { text: 'Unclear next steps', tag: 'Low' }]),
      opportunities: JSON.stringify([{ id: 'opp-med-3a', name: 'Clear flow and estimated times', tag: 'Medium' }]),
      backStageActions: 'Run clinic\nRun labs\nDocument in EHR\nCoordinate with flight surgeon',
      systems: 'EHR\nLab\nImaging',
      relatedProcesses: 'Aviation medicine',
    }),
    emptyPhase({
      id: 'demo-phase-med-4',
      journeyId: 'demo-journey-medical',
      order: 4,
      title: 'Results & Review',
      description: 'Results are compiled and reviewed; findings communicated.',
      customerJobs: JSON.stringify([{ text: 'Receive clear results', tag: 'Functional' }, { text: 'Understand implications', tag: 'Functional' }, { text: 'Know what happens next', tag: 'Emotional' }]),
      frontStageActions: 'Receive results (portal or call)\nFollow-up if needed\nDiscuss with physician',
      struggles: JSON.stringify([{ text: 'Delay in results or communication', tag: 'High' }]),
      opportunities: JSON.stringify([{ id: 'opp-med-4a', name: 'Structured results and next-step communication', tag: 'High' }]),
      backStageActions: 'Review results\nFlight surgeon sign-off\nReport to programme\nDocument',
      systems: 'EHR\nReporting',
      relatedProcesses: 'Aviation medicine\nProgramme',
    }),
    // —— Facility Management ——
    emptyPhase({
      id: 'demo-phase-fac-1',
      journeyId: 'demo-journey-facilitymgmt',
      order: 1,
      title: 'Shift Handover & Briefing',
      description: 'Operations team receives handover and priorities for the day.',
      customerJobs: JSON.stringify([{ text: 'Understand today\'s events and priorities', tag: 'Functional' }, { text: 'Know any issues carried over', tag: 'Functional' }, { text: 'Feel confident to start the shift', tag: 'Emotional' }]),
      frontStageActions: 'Attend handover meeting\nReview run sheets\nCheck incident log\nReceive keys and radios',
      struggles: JSON.stringify([{ text: 'Incomplete handover documentation', tag: 'Medium' }, { text: 'Conflicting priorities across events', tag: 'High' }]),
      internalStruggles: JSON.stringify([{ text: 'System doesn\'t link events to space requirements', tag: 'High' }]),
      opportunities: JSON.stringify([{ id: 'opp-fac-1a', name: 'Unified handover checklist and run sheet', tag: 'High' }]),
      backStageActions: 'Conduct handover\nUpdate incident log\nBrief security and catering',
      systems: 'Facility management\nCMMS',
      relatedProcesses: 'Operations\nSecurity',
    }),
    emptyPhase({
      id: 'demo-phase-fac-2',
      journeyId: 'demo-journey-facilitymgmt',
      order: 2,
      title: 'Pre-Event Inspections',
      description: 'Walk-through and checks before doors open.',
      customerJobs: JSON.stringify([{ text: 'Verify all spaces are ready', tag: 'Functional' }, { text: 'Identify and escalate issues', tag: 'Functional' }]),
      frontStageActions: 'Walk venue zones\nCheck HVAC and lighting\nVerify signage and wayfinding\nTest access and egress',
      struggles: JSON.stringify([{ text: 'Inspection findings not linked to work orders', tag: 'Medium' }]),
      opportunities: JSON.stringify([{ id: 'opp-fac-2a', name: 'Mobile inspection with photo evidence and auto-work order', tag: 'High' }]),
      backStageActions: 'Log defects\nCreate work orders\nCoordinate with vendors',
      systems: 'CMMS\nBMS',
      relatedProcesses: 'Maintenance\nHousekeeping',
    }),
    emptyPhase({
      id: 'demo-phase-fac-3',
      journeyId: 'demo-journey-facilitymgmt',
      order: 3,
      title: 'Event In Progress',
      description: 'Ongoing support during the event.',
      customerJobs: JSON.stringify([{ text: 'Respond to incidents quickly', tag: 'Functional' }, { text: 'Keep event running smoothly', tag: 'Functional' }]),
      frontStageActions: 'Monitor venue\nRespond to calls\nCoordinate with event manager\nHandle ad-hoc requests',
      struggles: JSON.stringify([{ text: 'Multiple channels for reporting issues', tag: 'Medium' }, { text: 'Slow response to non-urgent requests', tag: 'Low' }]),
      opportunities: JSON.stringify([{ id: 'opp-fac-3a', name: 'Single incident and request channel', tag: 'Medium' }]),
      backStageActions: 'Log incidents\nDispatch team\nUpdate run sheet',
      systems: 'Incident management\nEvent ops',
      relatedProcesses: 'Safety\nCatering',
    }),
    emptyPhase({
      id: 'demo-phase-fac-4',
      journeyId: 'demo-journey-facilitymgmt',
      order: 4,
      title: 'Post-Event & Close-Out',
      description: 'Event wrap-up and preparation for next day.',
      customerJobs: JSON.stringify([{ text: 'Close out event cleanly', tag: 'Functional' }, { text: 'Document issues for handover', tag: 'Functional' }]),
      frontStageActions: 'Secure venue\nComplete close-out checklist\nDocument incidents\nHand over to next shift',
      struggles: JSON.stringify([{ text: 'Incomplete close-out when running late', tag: 'Medium' }]),
      opportunities: JSON.stringify([{ id: 'opp-fac-4a', name: 'Digital close-out with mandatory sign-off', tag: 'Medium' }]),
      backStageActions: 'Update handover notes\nSchedule follow-up work\nBrief next shift',
      systems: 'Handover system\nCMMS',
      relatedProcesses: 'Operations',
    }),

    // —— Exhibitor Journey ——
    emptyPhase({
      id: 'demo-phase-exh-1',
      journeyId: 'demo-journey-exhibitor',
      order: 1,
      title: 'Stand Booking & Contract',
      description: 'Exhibitor selects space and completes booking.',
      customerJobs: JSON.stringify([{ text: 'Find the right stand location', tag: 'Functional' }, { text: 'Understand costs and inclusions', tag: 'Functional' }, { text: 'Secure a good spot before it\'s gone', tag: 'Emotional' }]),
      frontStageActions: 'Browse floor plan\nSelect stand package\nSubmit application\nSign contract\nPay deposit',
      struggles: JSON.stringify([{ text: 'Unclear pricing and package options', tag: 'High' }, { text: 'Floor plan hard to interpret', tag: 'Medium' }]),
      internalStruggles: JSON.stringify([{ text: 'Manual contract generation delays', tag: 'Medium' }]),
      opportunities: JSON.stringify([{ id: 'opp-exh-1a', name: 'Interactive floor plan with real-time availability', tag: 'High' }, { id: 'opp-exh-1b', name: 'Clear package comparison and e-sign', tag: 'Medium' }]),
      backStageActions: 'Allocate stands\nGenerate contracts\nProcess payments',
      systems: 'Event management\nCRM\nFinance',
      relatedProcesses: 'Sales\nFinance',
    }),
    emptyPhase({
      id: 'demo-phase-exh-2',
      journeyId: 'demo-journey-exhibitor',
      order: 2,
      title: 'Pre-Event Planning',
      description: 'Exhibitor plans stand build, services, and logistics.',
      customerJobs: JSON.stringify([{ text: 'Order services and utilities', tag: 'Functional' }, { text: 'Understand build rules and deadlines', tag: 'Functional' }]),
      frontStageActions: 'Receive exhibitor manual\nOrder electricity, AV, furniture\nSubmit stand design for approval\nBook contractor access',
      struggles: JSON.stringify([{ text: 'Multiple forms and portals', tag: 'High' }, { text: 'Unclear deadlines', tag: 'Medium' }]),
      opportunities: JSON.stringify([{ id: 'opp-exh-2a', name: 'Single exhibitor hub with checklist and deadlines', tag: 'High' }]),
      backStageActions: 'Review designs\nProcess orders\nCoordinate with contractors',
      systems: 'Exhibitor management\nOrders',
      relatedProcesses: 'Operations\nHealth & safety',
    }),
    emptyPhase({
      id: 'demo-phase-exh-3',
      journeyId: 'demo-journey-exhibitor',
      order: 3,
      title: 'Bump-In & Setup',
      description: 'Exhibitor arrives and builds stand.',
      customerJobs: JSON.stringify([{ text: 'Get in and out efficiently', tag: 'Functional' }, { text: 'Resolve any last-minute issues', tag: 'Functional' }]),
      frontStageActions: 'Check in and collect pass\nNavigate to stand\nCoordinate with contractors\nTest utilities',
      struggles: JSON.stringify([{ text: 'Long queues at check-in', tag: 'Medium' }, { text: 'Delayed utility hook-up', tag: 'High' }]),
      opportunities: JSON.stringify([{ id: 'opp-exh-3a', name: 'Pre-registration and express check-in', tag: 'Medium' }]),
      backStageActions: 'Process check-ins\nManage load-in schedule\nSupport exhibitors',
      systems: 'Access control\nOperations',
      relatedProcesses: 'Security\nContractors',
    }),
    emptyPhase({
      id: 'demo-phase-exh-4',
      journeyId: 'demo-journey-exhibitor',
      order: 4,
      title: 'Show Days',
      description: 'Exhibitor runs stand during the event.',
      customerJobs: JSON.stringify([{ text: 'Engage visitors effectively', tag: 'Functional' }, { text: 'Get support when needed', tag: 'Functional' }]),
      frontStageActions: 'Staff stand\nEngage visitors\nCapture leads\nAttend sessions',
      struggles: JSON.stringify([{ text: 'Lead capture not integrated with CRM', tag: 'Medium' }]),
      opportunities: JSON.stringify([{ id: 'opp-exh-4a', name: 'Integrated lead capture and analytics', tag: 'Medium' }]),
      backStageActions: 'Exhibitor support desk\nVenue services\nLead data export',
      systems: 'Lead capture\nCRM',
      relatedProcesses: 'Operations',
    }),
    emptyPhase({
      id: 'demo-phase-exh-5',
      journeyId: 'demo-journey-exhibitor',
      order: 5,
      title: 'Bump-Out',
      description: 'Exhibitor dismantles and exits.',
      customerJobs: JSON.stringify([{ text: 'Dismantle and leave on schedule', tag: 'Functional' }, { text: 'Avoid penalties', tag: 'Functional' }]),
      frontStageActions: 'Dismantle stand\nReturn passes\nExit venue',
      struggles: JSON.stringify([{ text: 'Congestion and delays', tag: 'Medium' }]),
      opportunities: JSON.stringify([{ id: 'opp-exh-5a', name: 'Staggered bump-out with real-time status', tag: 'Low' }]),
      backStageActions: 'Manage bump-out\nInspect stands\nProcess final invoices',
      systems: 'Operations\nFinance',
      relatedProcesses: 'Contractors',
    }),

    // —— Corporate Booking ——
    emptyPhase({
      id: 'demo-phase-corp-1',
      journeyId: 'demo-journey-corporatebook',
      order: 1,
      title: 'Inquiry & Discovery',
      description: 'Corporate contact explores venue and submits inquiry.',
      customerJobs: JSON.stringify([{ text: 'Find suitable spaces for my event', tag: 'Functional' }, { text: 'Get a sense of cost and availability', tag: 'Functional' }, { text: 'Feel the venue matches our brand', tag: 'Emotional' }]),
      frontStageActions: 'Browse website\nView virtual tour\nSubmit inquiry form\nReceive initial response',
      struggles: JSON.stringify([{ text: 'Generic response and slow follow-up', tag: 'High' }, { text: 'No availability visibility', tag: 'Medium' }]),
      internalStruggles: JSON.stringify([{ text: 'Inquiries land in shared inbox', tag: 'Medium' }]),
      opportunities: JSON.stringify([{ id: 'opp-corp-1a', name: 'Instant availability checker and tailored proposal', tag: 'High' }]),
      backStageActions: 'Triage inquiries\nCheck availability\nAssign account manager',
      systems: 'CRM\nBooking system',
      relatedProcesses: 'Sales',
    }),
    emptyPhase({
      id: 'demo-phase-corp-2',
      journeyId: 'demo-journey-corporatebook',
      order: 2,
      title: 'Proposal & Site Visit',
      description: 'Proposal sent; client may visit venue.',
      customerJobs: JSON.stringify([{ text: 'Receive a clear, tailored proposal', tag: 'Functional' }, { text: 'See the space in person', tag: 'Functional' }]),
      frontStageActions: 'Receive proposal\nReview options\nSchedule site visit\nAttend visit',
      struggles: JSON.stringify([{ text: 'Proposal lacks flexibility', tag: 'Medium' }, { text: 'Site visit hard to schedule', tag: 'Low' }]),
      opportunities: JSON.stringify([{ id: 'opp-corp-2a', name: 'Configurable proposal and self-serve site visit booking', tag: 'Medium' }]),
      backStageActions: 'Prepare proposal\nCoordinate visit\nFollow up',
      systems: 'Proposal tool\nScheduling',
      relatedProcesses: 'Sales',
    }),
    emptyPhase({
      id: 'demo-phase-corp-3',
      journeyId: 'demo-journey-corporatebook',
      order: 3,
      title: 'Contract & Confirmation',
      description: 'Negotiation, contract, and deposit.',
      customerJobs: JSON.stringify([{ text: 'Sign contract and secure the date', tag: 'Functional' }, { text: 'Understand terms and inclusions', tag: 'Functional' }]),
      frontStageActions: 'Negotiate terms\nSign contract\nPay deposit\nReceive confirmation',
      struggles: JSON.stringify([{ text: 'Contract revisions slow', tag: 'Medium' }]),
      opportunities: JSON.stringify([{ id: 'opp-corp-3a', name: 'E-sign and integrated payment', tag: 'Medium' }]),
      backStageActions: 'Draft contract\nProcess payment\nUpdate booking system',
      systems: 'Legal\nFinance\nBooking',
      relatedProcesses: 'Legal\nFinance',
    }),

    // —— Launch Operations ——
    emptyPhase({
      id: 'demo-phase-launch-1',
      journeyId: 'demo-journey-launchops',
      order: 1,
      title: 'Mission Integration Kick-off',
      description: 'Customer satellite arrives; integration planning begins.',
      customerJobs: JSON.stringify([{ text: 'Understand integration requirements', tag: 'Functional' }, { text: 'Meet the team and process', tag: 'Social' }, { text: 'Feel confident in the partnership', tag: 'Emotional' }]),
      frontStageActions: 'Attend kick-off meeting\nReceive integration handbook\nReview interface requirements\nEstablish communication channels',
      struggles: JSON.stringify([{ text: 'Documentation spread across systems', tag: 'Medium' }, { text: 'Unclear interface and schedule', tag: 'High' }]),
      internalStruggles: JSON.stringify([{ text: 'Engineering and ops use different tools', tag: 'High' }]),
      opportunities: JSON.stringify([{ id: 'opp-launch-1a', name: 'Mission integration portal with checklist', tag: 'High' }]),
      backStageActions: 'Assign integration lead\nPrepare facilities\nSchedule reviews',
      systems: 'Mission management\nConfluence',
      relatedProcesses: 'Integration\nSafety',
    }),
    emptyPhase({
      id: 'demo-phase-launch-2',
      journeyId: 'demo-journey-launchops',
      order: 2,
      title: 'Satellite Processing',
      description: 'Spacecraft checked, fueled, and mated to launch vehicle.',
      customerJobs: JSON.stringify([{ text: 'Track progress and milestones', tag: 'Functional' }, { text: 'Participate in key reviews', tag: 'Functional' }]),
      frontStageActions: 'Attend pre-ship review\nWatch processing (remote or on-site)\nParticipate in readiness review',
      struggles: JSON.stringify([{ text: 'Limited visibility into processing status', tag: 'High' }]),
      opportunities: JSON.stringify([{ id: 'opp-launch-2a', name: 'Real-time processing status and milestone alerts', tag: 'High' }]),
      backStageActions: 'Process spacecraft\nRun tests\nDocument and report',
      systems: 'Processing\nTest systems',
      relatedProcesses: 'Integration\nQuality',
    }),
    emptyPhase({
      id: 'demo-phase-launch-3',
      journeyId: 'demo-journey-launchops',
      order: 3,
      title: 'Launch Campaign',
      description: 'Final countdown and launch.',
      customerJobs: JSON.stringify([{ text: 'Follow launch and deployment', tag: 'Functional' }, { text: 'Celebrate success with the team', tag: 'Social' }]),
      frontStageActions: 'Attend launch (remote or on-site)\nMonitor deployment\nReceive post-launch briefing',
      struggles: JSON.stringify([{ text: 'Communication gaps during scrubs', tag: 'Medium' }]),
      opportunities: JSON.stringify([{ id: 'opp-launch-3a', name: 'Clear scrub and recycle communication', tag: 'Medium' }]),
      backStageActions: 'Execute launch\nMonitor vehicle\nConfirm deployment',
      systems: 'Launch ops\nTelemetry',
      relatedProcesses: 'Launch\nMission ops',
    }),
    emptyPhase({
      id: 'demo-phase-launch-4',
      journeyId: 'demo-journey-launchops',
      order: 4,
      title: 'Post-Launch Handover',
      description: 'Orbit confirmation and mission handover to customer.',
      customerJobs: JSON.stringify([{ text: 'Receive orbit data and handover', tag: 'Functional' }, { text: 'Know how to operate the spacecraft', tag: 'Functional' }]),
      frontStageActions: 'Receive orbit determination data\nAttend handover meeting\nAccess mission data archive',
      struggles: JSON.stringify([{ text: 'Delayed data delivery', tag: 'Medium' }]),
      opportunities: JSON.stringify([{ id: 'opp-launch-4a', name: 'Automated orbit and data handover', tag: 'Medium' }]),
      backStageActions: 'Process telemetry\nGenerate handover pack\nArchive data',
      systems: 'Mission ops\nArchive',
      relatedProcesses: 'Mission ops',
    }),

    // —— Customer Onboarding ——
    emptyPhase({
      id: 'demo-phase-onboard-1',
      journeyId: 'demo-journey-onboarding',
      order: 1,
      title: 'Welcome & Kick-off',
      description: 'New customer receives welcome and is assigned a dedicated contact.',
      customerJobs: JSON.stringify([{ text: 'Know who to contact', tag: 'Functional' }, { text: 'Understand the onboarding timeline', tag: 'Functional' }, { text: 'Feel welcomed', tag: 'Emotional' }]),
      frontStageActions: 'Receive welcome email\nMeet account manager\nReview onboarding checklist\nAttend kick-off call',
      struggles: JSON.stringify([{ text: 'Slow first response after contract', tag: 'High' }]),
      internalStruggles: JSON.stringify([{ text: 'Handoff from sales to CS is manual', tag: 'Medium' }]),
      opportunities: JSON.stringify([{ id: 'opp-onboard-1a', name: 'Automated welcome and assigned CSM', tag: 'High' }]),
      backStageActions: 'Assign CSM\nPrepare welcome pack\nSchedule kick-off',
      systems: 'CRM\nCustomer portal',
      relatedProcesses: 'Sales handoff\nCustomer success',
    }),
    emptyPhase({
      id: 'demo-phase-onboard-2',
      journeyId: 'demo-journey-onboarding',
      order: 2,
      title: 'Technical Setup',
      description: 'Access to portals, documentation, and technical integration.',
      customerJobs: JSON.stringify([{ text: 'Get access to systems and docs', tag: 'Functional' }, { text: 'Understand integration options', tag: 'Functional' }]),
      frontStageActions: 'Receive portal access\nReview documentation\nComplete technical questionnaire\nAttend integration briefing',
      struggles: JSON.stringify([{ text: 'Documentation hard to find', tag: 'Medium' }, { text: 'API docs out of date', tag: 'High' }]),
      opportunities: JSON.stringify([{ id: 'opp-onboard-2a', name: 'Structured docs and API playground', tag: 'High' }]),
      backStageActions: 'Provision access\nUpdate docs\nSupport integration',
      systems: 'Portal\nDocs\nSupport',
      relatedProcesses: 'Engineering\nSupport',
    }),
    emptyPhase({
      id: 'demo-phase-onboard-3',
      journeyId: 'demo-journey-onboarding',
      order: 3,
      title: 'First Mission Planning',
      description: 'Customer plans first launch or mission.',
      customerJobs: JSON.stringify([{ text: 'Plan and schedule first mission', tag: 'Functional' }, { text: 'Understand timelines and constraints', tag: 'Functional' }]),
      frontStageActions: 'Discuss manifest options\nSelect launch slot\nComplete mission questionnaire\nReceive confirmation',
      struggles: JSON.stringify([{ text: 'Manifest visibility limited', tag: 'Medium' }]),
      opportunities: JSON.stringify([{ id: 'opp-onboard-3a', name: 'Self-serve manifest and slot selection', tag: 'Medium' }]),
      backStageActions: 'Confirm slot\nUpdate manifest\nBrief integration team',
      systems: 'Mission planning\nManifest',
      relatedProcesses: 'Sales\nIntegration',
    }),
    emptyPhase({
      id: 'demo-phase-onboard-4',
      journeyId: 'demo-journey-onboarding',
      order: 4,
      title: 'Ongoing Support Handover',
      description: 'Transition to BAU support and success model.',
      customerJobs: JSON.stringify([{ text: 'Know how to get support', tag: 'Functional' }, { text: 'Have a clear success plan', tag: 'Functional' }]),
      frontStageActions: 'Receive support guide\nReview success plan\nMeet support and CS team',
      struggles: JSON.stringify([{ text: 'Unclear escalation path', tag: 'Low' }]),
      opportunities: JSON.stringify([{ id: 'opp-onboard-4a', name: 'Clear support tiers and escalation', tag: 'Medium' }]),
      backStageActions: 'Document success plan\nBrief support team\nSchedule check-ins',
      systems: 'Support\nCRM',
      relatedProcesses: 'Support\nCustomer success',
    }),

    // —— Research Collaboration ——
    emptyPhase({
      id: 'demo-phase-collab-1',
      journeyId: 'demo-journey-collab',
      order: 1,
      title: 'Partner Identification & Outreach',
      description: 'Identifying and approaching potential R&D partners.',
      customerJobs: JSON.stringify([{ text: 'Find complementary capabilities', tag: 'Functional' }, { text: 'Assess strategic fit', tag: 'Functional' }]),
      frontStageActions: 'Research potential partners\nAttend conferences\nInitiate contact\nShare areas of interest',
      struggles: JSON.stringify([{ text: 'Cold outreach gets low response', tag: 'Medium' }]),
      internalStruggles: JSON.stringify([{ text: 'No central partner pipeline', tag: 'High' }]),
      opportunities: JSON.stringify([{ id: 'opp-collab-1a', name: 'Partner ecosystem map and outreach tracker', tag: 'Medium' }]),
      backStageActions: 'Evaluate inbound interest\nMaintain partner pipeline\nCoordinate NDAs',
      systems: 'CRM\nLegal',
      relatedProcesses: 'BD\nLegal',
    }),
    emptyPhase({
      id: 'demo-phase-collab-2',
      journeyId: 'demo-journey-collab',
      order: 2,
      title: 'Scoping & Agreement',
      description: 'Defining collaboration scope and terms.',
      customerJobs: JSON.stringify([{ text: 'Align on objectives and scope', tag: 'Functional' }, { text: 'Secure IP and commercial terms', tag: 'Functional' }]),
      frontStageActions: 'Workshop objectives\nDefine scope and milestones\nNegotiate IP and commercial terms\nSign agreement',
      struggles: JSON.stringify([{ text: 'IP negotiation takes too long', tag: 'High' }]),
      opportunities: JSON.stringify([{ id: 'opp-collab-2a', name: 'Template agreements and IP playbook', tag: 'Medium' }]),
      backStageActions: 'Draft agreement\nCoordinate legal\nDocument scope',
      systems: 'Legal\nProject management',
      relatedProcesses: 'Legal\nEngineering',
    }),
    emptyPhase({
      id: 'demo-phase-collab-3',
      journeyId: 'demo-journey-collab',
      order: 3,
      title: 'Joint Development',
      description: 'Collaborative R&D and testing.',
      customerJobs: JSON.stringify([{ text: 'Progress the work effectively', tag: 'Functional' }, { text: 'Maintain alignment across teams', tag: 'Social' }]),
      frontStageActions: 'Attend steering meetings\nShare progress and data\nParticipate in reviews\nResolve blockers',
      struggles: JSON.stringify([{ text: 'Data sharing and security friction', tag: 'High' }, { text: 'Timezone and scheduling', tag: 'Medium' }]),
      opportunities: JSON.stringify([{ id: 'opp-collab-3a', name: 'Secure data room and async updates', tag: 'High' }]),
      backStageActions: 'Run development\nTrack milestones\nReport to steering',
      systems: 'Project tools\nData sharing',
      relatedProcesses: 'Engineering\nProgramme',
    }),
    emptyPhase({
      id: 'demo-phase-collab-4',
      journeyId: 'demo-journey-collab',
      order: 4,
      title: 'Outcomes & Next Steps',
      description: 'Wrapping up the collaboration and deciding on follow-on.',
      customerJobs: JSON.stringify([{ text: 'Capture and share outcomes', tag: 'Functional' }, { text: 'Decide on next phase or spin-off', tag: 'Functional' }]),
      frontStageActions: 'Final review meeting\nDocument outcomes\nDiscuss follow-on options\nSign off',
      struggles: JSON.stringify([{ text: 'Outcomes not well documented', tag: 'Medium' }]),
      opportunities: JSON.stringify([{ id: 'opp-collab-4a', name: 'Structured outcome report and learnings', tag: 'Medium' }]),
      backStageActions: 'Compile report\nArchive project\nUpdate partner record',
      systems: 'Project\nCRM',
      relatedProcesses: 'BD\nEngineering',
    }),

    emptyPhase({
      id: 'demo-phase-med-5',
      journeyId: 'demo-journey-medical',
      order: 5,
      title: 'Clearance & Next Steps',
      description: 'Clearance decision and integration with crew readiness.',
      customerJobs: JSON.stringify([{ text: 'Receive clearance or clear path to it', tag: 'Functional' }, { text: 'Address any conditions if needed', tag: 'Functional' }]),
      frontStageActions: 'Receive clearance decision\nComplete any follow-up\nReturn to training or programme flow',
      struggles: JSON.stringify([{ text: 'Conditional clearance and follow-up complexity', tag: 'Medium' }]),
      opportunities: JSON.stringify([{ id: 'opp-med-5a', name: 'Integrated follow-up and retest tracking', tag: 'Medium' }]),
      backStageActions: 'Issue clearance\nUpdate crew records\nCoordinate with training\nArchive',
      systems: 'Crew system\nEHR',
      relatedProcesses: 'Crew ops\nTraining',
    }),
  ];

  const jobs = getDemoJobs();
  const phasesWithJobIds = phases.map((p) => ({
    ...p,
    jobIds: DEMO_PHASE_JOB_IDS[p.id] ?? [],
    customerJobs: p.customerJobs,
  }));
  const opportunities = buildOpportunitiesFromPhases(phasesWithJobIds, journeys, projects);

  const insights: Insight[] = [
    // NZICC
    { id: 'demo-insight-1', clientId: 'demo-client-nzicc', title: 'Event discovery fragmented across channels', description: 'Research shows attendees use multiple sources (Google, social, email) to find events but no single hub exists. 72% use 3+ sources.', priority: 'High', order: 0, createdAt: TS, updatedAt: TS },
    { id: 'demo-insight-2', clientId: 'demo-client-nzicc', title: 'Registration friction drives drop-off', description: 'Form length and unclear refund policy cited as top barriers. A/B tests suggest 15% conversion lift with shorter forms.', priority: 'High', order: 1, createdAt: TS, updatedAt: TS },
    { id: 'demo-insight-3', clientId: 'demo-client-nzicc', title: 'Networking is key value driver', description: 'Post-event surveys rank networking above content for repeat attendance. Pre-event matching requests up 40% YoY.', priority: 'Medium', order: 2, createdAt: TS, updatedAt: TS },
    { id: 'demo-insight-4', clientId: 'demo-client-nzicc', title: 'Session clashes drive agenda frustration', description: 'Overlapping sessions in multi-track events cause decision stress. 60% of attendees report missing preferred sessions due to clashes.', priority: 'High', order: 3, createdAt: TS, updatedAt: TS },
    { id: 'demo-insight-5', clientId: 'demo-client-nzicc', title: 'Post-event content delayed or scattered', description: 'Slides and recordings arrive late or across multiple platforms. Attendees want one place to catch up within 48 hours.', priority: 'Medium', order: 4, createdAt: TS, updatedAt: TS },
    { id: 'demo-insight-6', clientId: 'demo-client-nzicc', title: 'Ticketing queue anxiety and drop-off', description: 'Queue timeouts and perceived unfairness in onsale drive frustration. Fans cite scalping as top concern for high-demand shows.', priority: 'High', order: 5, createdAt: TS, updatedAt: TS },
    // Rocket Lab
    { id: 'demo-insight-7', clientId: 'demo-client-rocketlab', title: 'Application clarity reduces qualified drop-off', description: 'Candidates with clear rubrics and examples complete applications at 2x rate. Unclear criteria drives support load.', priority: 'High', order: 0, createdAt: TS, updatedAt: TS },
    { id: 'demo-insight-8', clientId: 'demo-client-rocketlab', title: 'Medical clearance process opaque', description: 'Candidates report anxiety around medical timeline. Integrated tracking and status visibility would reduce enquiries.', priority: 'Medium', order: 1, createdAt: TS, updatedAt: TS },
    { id: 'demo-insight-9', clientId: 'demo-client-rocketlab', title: 'Candidates want fair and transparent process', description: 'Perceived bias in selection drives disengagement. Clear criteria and feedback loops improve trust and completion rates.', priority: 'High', order: 2, createdAt: TS, updatedAt: TS },
  ];

  // Link insights to jobs (thematic match)
  const insightToJobIds: Record<string, string[]> = {
    'demo-insight-1': ['demo-job-1', 'demo-job-4'],
    'demo-insight-2': ['demo-job-2'],
    'demo-insight-3': ['demo-job-3'],
    'demo-insight-4': ['demo-job-3'],
    'demo-insight-5': ['demo-job-6'],
    'demo-insight-6': ['demo-job-5'],
    'demo-insight-7': ['demo-job-7'],
    'demo-insight-8': ['demo-job-9', 'demo-job-10'],
    'demo-insight-9': ['demo-job-7', 'demo-job-8'],
  };
  const jobsWithInsights = jobs.map((j) => {
    const insightIds = Object.entries(insightToJobIds)
      .filter(([, ids]) => ids.includes(j.id))
      .map(([id]) => id);
    return { ...j, insightIds };
  });

  // Link jobs to opportunities (thematic match: opportunity addresses job struggles)
  const opportunityToJobIds: Record<string, string[]> = {
    'opp-conf-1a': ['demo-job-1'],
    'opp-conf-2a': ['demo-job-2'],
    'opp-conf-2b': ['demo-job-2'],
    'opp-conf-3a': ['demo-job-3'],
    'opp-conf-5a': ['demo-job-6'],
    'opp-concert-1a': ['demo-job-4'],
    'opp-concert-2a': ['demo-job-5'],
    'opp-concert-4a': ['demo-job-5'],
    'opp-astro-1a': ['demo-job-7'],
    'opp-astro-2a': ['demo-job-8'],
    'opp-med-1a': ['demo-job-9'],
    'opp-med-2a': ['demo-job-10'],
    'opp-fac-1a': ['demo-job-11'],
    'opp-fac-2a': ['demo-job-12'],
  };
  const jobIdSet = new Set(jobs.map((j) => j.id));
  const opportunitiesWithJobs = opportunities.map((o) => ({
    ...o,
    linkedJobIds: (opportunityToJobIds[o.id] ?? []).filter((id) => jobIdSet.has(id)),
  }));

  return {
    clients,
    projects,
    journeys,
    phases: phasesWithJobIds,
    jobs: jobsWithInsights,
    insights,
    opportunities: opportunitiesWithJobs,
    cellComments: {},
  };
}
